### ISSUE TITLE
JMA CFRadial does not have the expected field names

### ISSUE THREAD

**Issue by jfigui** [openradar/asean2024-pyrad-course#12]
Hi @wolfidan ,

I have pushed the JMA data into the repository. There is an issue because the field names are not what we would expect from a CFRadial file. I am working on a solution. I will push Pyrad-dev when this is ready.

**Comment by wolfidan** [comment]
@jfigui 

It is still not working on the binder:

- master file: Z__C_RJTD_20230801200000_RDR_JMAGPV_RS47937_Gar0p250km0p35deg_PRref_N11_ANAL_cfrad.nc
Field DBZH not present in both radars (/srv/conda/envs/notebook/lib/python3.9/site-packages/pyart/util/radar_utils.py:431)
-- Process level: l00
--- Processing dataset: dBZ
---- Processing product: PPI_EL00
 Field type reflectivity not available in data set. Skipping product PPI_IMAGE (/srv/conda/envs/notebook/lib/python3.9/site-packages/pyrad/prod/process_vol_products.py:769)
---- Processing product: PPI_EL01
 Field type reflectivity not available in data set. Skipping product PPI_IMAGE (/srv/conda/envs/notebook/lib/python3.9/site-packages/pyrad/prod/process_vol_products.py:769)
---- Processing product: BSCOPE_EL00
 Field type reflectivity not available in data set. Skipping product BSCOPE_IMAGE (/srv/conda/envs/notebook/lib/python3.9/site-packages/pyrad/prod/process_vol_products.py:2452)
---- Processing product: RHI_AZ000
 Field type reflectivity not available in data set. Skipping product PSEUDORHI_IMAGE (/srv/conda/envs/notebook/lib/python3.9/site-packages/pyrad/prod/process_vol_products.py:1181)
---- Processing product: HIST
 Field type reflectivity not available in data set. Skipping product HISTOGRAM (/srv/conda/envs/notebook/lib/python3.9/site-packages/pyrad/prod/process_vol_products.py:2542)
---- Processing product: PPI_MAP_EL00
 Field type reflectivity not available in data set. Skipping product PPI_MAP (/srv/conda/envs/notebook/lib/python3.9/site-packages/pyrad/prod/process_vol_products.py:864)
---- Processing product: PPI_MAP_EL01
 Field type reflectivity not available in data set. Skipping product PPI_MAP (/srv/conda/envs/notebook/lib/python3.9/site-packages/pyrad/prod/process_vol_products.py:864)
---- Processing product: AZ000_ELE00_6
 Field type reflectivity not available in data set. Skipping product PLOT_ALONG_COORD (/srv/conda/envs/notebook/lib/python3.9/site-packages/pyrad/prod/process_vol_products.py:2268)

**Comment by wolfidan** [comment]
Ho I see it still uses the old pyrad version (before my last week release), I will try to fix that

**Comment by wolfidan** [comment]
It is solved in the latest version of the binder, I think we can close the issue
