### ISSUE TITLE
local installation of the environment working with mini-forge?

### ISSUE THREAD

**Issue by jfigui** [openradar/asean2024-pyrad-course#13]
Hi @wolfidan ,
I am trying to install the conda environment and I have mini-forge instead of conda. mini-forge only can access the conda-forge channel. 

At the moment the situation is that it is stack forever trying to solve the environment and then it crashes. 

Do you know the reason? Is there any package that should be installed and it is not available in the conda-forge channel?

Here you have the message:

Collecting package metadata (repodata.json): done
Solving environment: | Segmentation fault (core dumped)

**Comment by wolfidan** [comment]
Hi @jfigui ,

I think it might have to do with certifi in the environment.yml. 
I commited a new environment.yml, let me know if it works beter

**Comment by wolfidan** [comment]
Hi @jfigui 

I just tested it and it works well with miniforge. The only annoying problem is that pydda installs the arm version of pyart and pyrad the MeteoSwiss version. A fix is provided in the README.
