### ISSUE TITLE
Pyrad config files to add

### ISSUE THREAD

**Issue by jfigui** [openradar/asean2024-pyrad-course#7]
Hi @wolfidan ,

I thought that before committing anything that we later may won to remove it would be better to discuss here which config files we want to be available for the course. There are those you already prepared. There are others that I prepared for the generic [pyrad_course](https://github.com/openradar/pyrad_course) .

We may want to develop others or decide to remove some. So here is the list:

- [x]  Attenuation (already committed)
- [x]  DDA  (already committed)
- [x]  Hydrometeor classification (mf_odim_coll_hydro in pyrad_course)
- [x]  Melting layer detection (mf_odim_ml in pyrad_course)
- [x]  Quasi-vertical profiles (mf_odim_coll_qvp in pyrad_course)
- [x]  Rainfall rate estimation (mf_odim_coll_rr in pyrad_course)
- [x]  Doppler velocity processing (mf_pag_mtcy_doppler in pyrad_course)
- [x]  Clutter suppression (mf_pam_mtcy_filter in pyrad_course)
- [x]  Radar data gridding (mf_pam_mtcy_grid in pyrad_course)
- [x]  KDP/PhiDP processing (mf_pam_mtcy_kdp in pyrad_course)
- [x]  Radar volume data plotting (mf_pam_mtcy_plot_vol in pyrad_course)

Let me know what you think.

**Comment by jfigui** [comment]
@wolfidan ,

I have committed the config files together with the data needed. To note that only the gridding and the volume data plotting use the JMA data because with just two elevations of well cleaned data not much can be done in terms of time series or volumetric processing. We could discuss whether rainfall rate estimation could use the Japanese data and eventually the hydrometeor classification although I think the hydrometeor classification in a tropical environment is not particularly interesting.

Let me know your opinion.

**Comment by wolfidan** [comment]
Hi @jfigui, honestly I would just leave it as is. It's nice to have local data, but in the end it is not crucial to understand how pyrad works. I think hydrometeor classification with Swiss or French data is much more interesting indeed.
